# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_remotcontrol(object):
    def setupUi(self, remotcontrol):
        remotcontrol.setObjectName("remotcontrol")
        remotcontrol.resize(337, 663)
        self.centralwidget = QtWidgets.QWidget(remotcontrol)
        self.centralwidget.setObjectName("centralwidget")
        self.Button_Power = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Power.setGeometry(QtCore.QRect(50, 20, 81, 31))
        self.Button_Power.setObjectName("Button_Power")
        self.Button_mute = QtWidgets.QPushButton(self.centralwidget)
        self.Button_mute.setGeometry(QtCore.QRect(200, 20, 93, 31))
        self.Button_mute.setObjectName("Button_mute")
        self.Button_Netflix = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Netflix.setGeometry(QtCore.QRect(120, 440, 93, 28))
        self.Button_Netflix.setObjectName("Button_Netflix")
        self.Button_sing = QtWidgets.QPushButton(self.centralwidget)
        self.Button_sing.setGeometry(QtCore.QRect(120, 480, 93, 28))
        self.Button_sing.setObjectName("Button_sing")
        self.Button_hulu = QtWidgets.QPushButton(self.centralwidget)
        self.Button_hulu.setGeometry(QtCore.QRect(120, 520, 93, 28))
        self.Button_hulu.setObjectName("Button_hulu")
        self.Button_Vudu = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Vudu.setGeometry(QtCore.QRect(120, 560, 93, 28))
        self.Button_Vudu.setObjectName("Button_Vudu")
        self.Button_Right = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Right.setGeometry(QtCore.QRect(230, 310, 93, 28))
        self.Button_Right.setObjectName("Button_Right")
        self.Button_Left = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Left.setGeometry(QtCore.QRect(20, 310, 93, 28))
        self.Button_Left.setObjectName("Button_Left")
        self.Button_Down = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Down.setGeometry(QtCore.QRect(120, 370, 93, 28))
        self.Button_Down.setObjectName("Button_Down")
        self.Button_Up = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Up.setGeometry(QtCore.QRect(120, 250, 93, 28))
        self.Button_Up.setObjectName("Button_Up")
        self.Button_Home = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Home.setGeometry(QtCore.QRect(120, 300, 93, 51))
        self.Button_Home.setObjectName("Button_Home")
        self.imglabel = QtWidgets.QLabel(self.centralwidget)
        self.imglabel.setGeometry(QtCore.QRect(40, 60, 251, 181))
        self.imglabel.setObjectName("imglabel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 350, 61, 61))
        self.label.setObjectName("label")
        remotcontrol.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(remotcontrol)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 337, 26))
        self.menubar.setObjectName("menubar")
        remotcontrol.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(remotcontrol)
        self.statusbar.setObjectName("statusbar")
        remotcontrol.setStatusBar(self.statusbar)

        self.retranslateUi(remotcontrol)
        QtCore.QMetaObject.connectSlotsByName(remotcontrol)

    def retranslateUi(self, remotcontrol):
        _translate = QtCore.QCoreApplication.translate
        remotcontrol.setWindowTitle(_translate("remotcontrol", "MainWindow"))
        self.Button_Power.setText(_translate("remotcontrol", "Power"))
        self.Button_mute.setText(_translate("remotcontrol", "Mute"))
        self.Button_Netflix.setText(_translate("remotcontrol", "Netflix"))
        self.Button_sing.setText(_translate("remotcontrol", "Sing"))
        self.Button_hulu.setText(_translate("remotcontrol", "Hulu"))
        self.Button_Vudu.setText(_translate("remotcontrol", "VUDU"))
        self.Button_Right.setText(_translate("remotcontrol", "Right"))
        self.Button_Left.setText(_translate("remotcontrol", "Left"))
        self.Button_Down.setText(_translate("remotcontrol", "V/ Down"))
        self.Button_Up.setText(_translate("remotcontrol", "V/ Up"))
        self.Button_Home.setText(_translate("remotcontrol", "HOME"))
        self.imglabel.setText(_translate("remotcontrol", "<html><head/><body><p><img src=\":/newPrefix/power.jpg\"/></p></body></html>"))
        self.label.setText(_translate("remotcontrol", "<html><head/><body><p><img src=\":/newPrefix/volumemute.webp\"/></p></body></html>"))

